# Generated by Django 6.0.4 on 2026-04-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patologias',
            fields=[
                ('id_patologia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_patologia', models.CharField(max_length=100)),
            ],
        ),
    ]
