# Generated by Django 6.0.4 on 2026-06-08 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_clase', models.DateTimeField()),
                ('hora_inicio_clase', models.TimeField()),
                ('hora_fin_clase', models.TimeField()),
                ('cupo_maximo_clase', models.IntegerField()),
                ('descripcion_clase', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patologias',
            fields=[
                ('id_patologia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_patologia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=100)),
                ('cantidad_clases', models.IntegerField()),
                ('precio_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_plan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario'), ('Entrenador', 'Entrenador')], default='Usuario', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('comprobante_pago', models.CharField(max_length=100)),
                ('estado_pago', models.CharField(choices=[('Completado', 'Completado'), ('Pendiente', 'Pendiente'), ('Fallido', 'Fallido')], default='Pendiente', max_length=20)),
                ('id_usuario_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.planes')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('pnombre_usuario', models.CharField(max_length=100)),
                ('snombre_usuario', models.CharField(max_length=100)),
                ('papellido_usuario', models.CharField(max_length=100)),
                ('sapellido_usuario', models.CharField(max_length=100)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
                ('cedula_usuario', models.CharField(max_length=20, unique=True)),
                ('telefono_usuario', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento_usuario', models.DateField()),
                ('genero_usuario', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Otro', 'Otro')], max_length=5)),
                ('fecha_creacion_usuario', models.DateTimeField(auto_now_add=True)),
                ('activo_usuario', models.BooleanField(default=True)),
                ('creditos_usuario', models.IntegerField(default=0)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_roles',
            fields=[
                ('id_usuario_rol', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.roles')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_planes',
            fields=[
                ('id_usuario_plan', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_plan', models.DateField()),
                ('fecha_fin_plan', models.DateField()),
                ('clases_restantes', models.IntegerField()),
                ('activo_usuario_plan', models.BooleanField(default=True)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.planes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_patologias',
            fields=[
                ('id_usuario_patologia', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones_patologia', models.TextField()),
                ('id_patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patologias')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evaluacion', models.DateField()),
                ('fecha_registro_resultado', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repeticiones', models.IntegerField()),
                ('rondas', models.IntegerField()),
                ('unidad', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2)),
                ('comentarios_resultado', models.TextField(blank=True, null=True)),
                ('id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.movimientos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado_reservas', models.CharField(choices=[('Asistido', 'Asistido'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clases')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion_diaria',
            fields=[
                ('id_planificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
                ('entrenamiento', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='clases',
            name='id_entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases_impartidas', to='backend.usuarios'),
        ),
        migrations.AddField(
            model_name='clases',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_reservadas', to='backend.usuarios'),
        ),
        migrations.CreateModel(
            name='Biometria',
            fields=[
                ('id_biometria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_biometria', models.CharField(max_length=100)),
                ('huella_hash', models.CharField(max_length=100)),
                ('fecha_registro_biometria', models.DateTimeField(auto_now_add=True)),
                ('activo_biometria', models.BooleanField(default=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id_acceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('tipo_acceso', models.CharField(max_length=100)),
                ('permitido_acceso', models.BooleanField(default=True)),
                ('motivo_acceso', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEntrenador',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.CharField(choices=[('06:00', '6:00 AM'), ('07:00', '7:00 AM'), ('08:00', '8:00 AM'), ('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM'), ('19:00', '7:00 PM')], max_length=5)),
                ('hora_fin', models.CharField(max_length=5)),
                ('activo', models.BooleanField(default=True)),
                ('id_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='backend.usuarios')),
            ],
            options={
                'unique_together': {('id_entrenador', 'fecha', 'hora_inicio')},
            },
        ),
    ]
