# Generated by Django 6.0.4 on 2026-04-23 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_clases_movimientos_planes_roles_usuarios_pagos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_auth_user',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='genero_usuario',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Otro', 'Otro')], max_length=5),
        ),
    ]
