# Generated by Django 6.0.4 on 2026-06-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_invitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='sapellido_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='snombre_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
