# Generated by Django 6.0.4 on 2026-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_usuarios_id_auth_user_usuarios_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellido_usuario',
            new_name='papellido_usuario',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre_usuario',
            new_name='pnombre_usuario',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='sapellido_usuario',
            field=models.CharField(default='prueba', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='snombre_usuario',
            field=models.CharField(default='prueba', max_length=100),
            preserve_default=False,
        ),
    ]
