# Generated by Django 6.0.4 on 2026-05-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_apellido_usuario_usuarios_papellido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='creditos_usuario',
            field=models.IntegerField(default=1),
        ),
    ]
