# Generated by Django 6.0.4 on 2026-05-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_usuarios_creditos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='creditos_usuario',
            field=models.IntegerField(default=0),
        ),
    ]
