# Generated by Django 6.0.4 on 2026-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_usuarios_creditos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados',
            name='unidad',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='comentarios_resultado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='fecha_evaluacion',
            field=models.DateField(),
        ),
    ]
