# Generated by Django 6.0.4 on 2026-06-02 23:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_resultados_unidad_usuarios_altura_usuarios_peso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion_diaria',
            name='id_clase',
        ),
        migrations.RemoveField(
            model_name='planificacion_diaria',
            name='observaciones_planificacion_diaria',
        ),
        migrations.AddField(
            model_name='planificacion_diaria',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.usuarios'),
        ),
        migrations.AddField(
            model_name='planificacion_diaria',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planificacion_diaria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planificacion_diaria',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
