# Generated by Django 6.0.4 on 2026-06-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_planificacion_diaria_id_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion_diaria',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
